# Generated by Django 2.2 on 2021-06-17 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('cp', models.CharField(max_length=5)),
                ('address', models.CharField(max_length=128)),
                ('capacity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('numberRatings', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=128)),
                ('lan', models.FloatField(default=0)),
                ('lon', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('init', models.DateTimeField(default=None)),
                ('end', models.DateTimeField(default=None)),
                ('rated', models.BooleanField(default=False)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easyrent.Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('confirmType', models.BooleanField(default=False)),
                ('text', models.CharField(max_length=512)),
                ('newInit', models.DateTimeField(default=None, null=True)),
                ('newEnd', models.DateTimeField(default=None, null=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('rent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='easyrent.Rent')),
                ('reserver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
